### ISSUE TITLE
Appendix N.2 omits fractional time expressions.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#188]
Appendix N.2 [1] describes the cases when time expressions include frames and subframes, and when it includes ticks, but not when it includes fractions of seconds. This usage is present in EBU-TT-D [2].

[1] http://www.w3.org/TR/ttml1/#time-expression-semantics-media
[2] https://tech.ebu.ch/docs/tech/tech3380.pdf

This could be fixed by adding the following alternative equation for M in the green box in this section immediately after the equation that uses frames and subFrames:

++++
OR

M = referenceBegin + 3600 \* hours + 60 \* minutes + seconds + fraction
++++

and changing

---
>> the hours, minutes, seconds, frames, subFrames components are extracted from time expression if present, or zero if not present;

to 

> the hours, minutes, seconds, frames, subFrames, fraction components are extracted from time expression if present, or zero if not present;

One could argue that this interpretation is obvious and does not require elaboration however I think it should be present for completeness. Otherwise when this appendix is made normative it could be interpreted that fractions of seconds are not permitted in time expressions when the timeBase is media, which I believe would be an error.

(raised by Nigel Megitt on 2014-05-02)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/306

**Comment by nigelmegitt** [comment]
See also w3c/ttml2#165.

[Meeting 2017-01-12] @skynavga to make the proposed change or add a note clarifying that the seconds includes any fractional component.
