### ISSUE TITLE
Use of application default frameRateMultipler, subFrameRate.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#192]
The defaulting rules for frameRate allow use of a default application specific value if frameRate is not specified, or 30 if no default application value applies. If a default application value is used, then a potential default application value should also be used with frameRateMultiplier and subFrameRate as well. However, the current defaulting language for these two parameters merely states that "1 1" and "1" be the default values respectively.

This should be fixed in an errata for TTML1.0SE and fixed inline in TTML2.

(raised by Glenn Adams on 2014-08-08)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/333

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Agreed to proceed.
