### ISSUE TITLE
Handling forward interoperability of attribute extensions in TT namespaces.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#196]
Although there was an intent to permit forward interop in the presence of attribute extensions in TT namespaces (in future versions, like TTML2), this was not satisfactorily document in TTML1 Section 4 [1] step 3, which presently states:

"3. pruning all attribute information items having expanded names such that the namespace URI of the expanded names are not listed in Table 1 - Namespaces,"

In order to resolve, this needs to be changed to read:

"3. pruning all attribute information items having expanded names such that the namespace URI of the expanded names are not listed in Table 1 - Namespaces, or, if listed in Table 1 - Namespaces, are not members of the collection of attributes defined by the associated Abstract Document Type for use with the owning element information item,"

Note that step 1 already handles this case for element information items:

"1. pruning all element information items whose names are not members of the collection of element types defined by the associated Abstract Document Type, then"

[1] http://www.w3.org/TR/2013/REC-ttml1-20130924/#ttml-content-doctype

(raised by Glenn Adams on 2015-01-01)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/362

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Agreed to proceed.
