### ISSUE TITLE
The [Construct Intermediate Document] process erroneously prunes empty <br> elements.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#197]
The [construct intermediate document] process says:

"2. evaluating this sub-tree in a postorder traversal, prune elements if
they are not a Content element, if they are temporally inactive, if they
are empty, or if they aren't associated with region R according to the
[associate region] procedure;"

This means that any empty <br> element e.g. "<br/>" is pruned, resulting in it having no effect. This isn't the correct behaviour because empty <br> elements should create line breaks and therefore have an effect.

This applies to TTML1, TTML1SE and TTML2.

(raised by Nigel Megitt on 2015-01-29)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/368

**Comment by nigelmegitt** [comment]
Related also to w3c/ttml2#212.

[Meeting 2017-01-12] Agreed that br elements should not be pruned from ISDs.
