### ISSUE TITLE
Missing XML declaration.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#199]
In the schema file ttml1-styling.xsd the introducing line <?xml version="1.0" encoding="utf-8"?> is missing

(raised by Pierre-Anthony Lemieux on 2015-03-19)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/376

**Comment by nigelmegitt** [comment]
@skynavga please add the commit reference if this is fixed, and then close if done?
