### ISSUE TITLE
Add errata for initial value fallback language.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#200]
Add errata to back-port new language from TTML2 10.4.4.2 step (6) that deals with initial value fallback that was accidentally omitted from TTML1 8.4.4.2 step (6).

(raised by Glenn Adams on 2015-07-16)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/399

**Comment by palemieux** [comment]
@skynavga What is the problem with TTML1 8.4.4.2 step (6) as currently written?

**Comment by palemieux** [comment]
It looks like this refers specifically to #217 and w3c/ttml2#213
