### ISSUE TITLE
Agent and actor circular references.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#201]
A ttm:agent can contain a ttm:actor. A ttm:actor can reference a ttm:agent. If an actor references its own parent agent then that would create a scenario that needs special handling in simple or naive implementations.

A major structural change to TTML1 is unwarranted at this stage however an editorial note to warn implementors of this would be helpful.

Alternatively an erratum prohibiting this scenario could be added - it doesn't have any obvious semantic meaning. Even if an actor plays himself, like Steve Coogan in The Trip playing Steve Coogan, the correct structure would be to have an agent whose type is "person", say xml:id="steveCooganTheActor" and an agent whose type is "character", say xml:id="steveCooganTheCharacter" that contains an actor whose agent="steveCooganTheActor".

(raised by Nigel Megitt on 2015-08-04)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/401

**Comment by cconcolato** [comment]
It looks like the action should be done on TTML2 too.

**Comment by palemieux** [comment]
While the semantics of circular references are not defined, it is not clear to me that they should be forbidden. See note suggested in the PR.

**Comment by skynavga** [comment]
I believe it should be forbidden for the same reason that we write

>A loop in a sequence of chained style references must be considered an error.

**Comment by palemieux** [comment]
> I believe it should be forbidden for the same reason that we write
>> A loop in a sequence of chained style references must be considered an error.

I do not disagree that it must have been the intent. Stating _must be considered an error_ would potentially make existing processors non-conformant.

What about: _A `ttm:actor` element should not reference its parent `ttm:agent` element. Such circular relationships were erroneously permitted in previous versions of this specification, and are now deprecated._
