### ISSUE TITLE
Clarify meaning of percentage with writing mode relative edge terms in tts:padding.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml1#205]
Initially reported by Andreas Tai.

The question here is, for tts:padding="1% 2% 3% 4%" are the values related to absolute height and width or writing mode relative dimensions?

**Comment by nigelmegitt** [comment]
See also w3c/ttml2#144.

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Agreed to leave substantive definition the same but add clarification note that the percentages are relative to the absolute width and height of the region, i.e. the first and second component of the tts:extent. Also that if the before and after edges resolve to vertical dimensions then the percentages relate to height and if they resolve to horizontal dimensions then the percentages relate to width. Similarly for start and end edges.
