### ISSUE TITLE
Use of 'em' units in tts:fontSize on region element is not well defined.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml1#206]
§8.2.9 needs to place a constraint on the use of 'em' units when expressing tts:fontSize on a region element; alternatively, it could specify that 1em is equal to the initial value of tts:fontSize, namely, 1c, for the purpose of resolving an 'em' unit based font size

**Comment by palemieux** [comment]
> alternatively, it could specify that 1em is equal to the initial value of tts:fontSize, namely, 1c, for the purpose of resolving an 'em' unit based font size

+1

**Comment by skynavga** [comment]
actually, i now think it is problematic to define this alternative, since resolving em requires a computed font size on the parent, which, in TTML1 does not exist, i.e., there is no parent (or ancestor) of region for which a computed font size exists

**Comment by palemieux** [comment]
>  since resolving em requires a computed font size on the parent, which, in TTML1 does not exist,

As stated above, the problem is to compute "<x>em" on region. If "<x>em" is defined as "<x>c" (only on region) then it can always be computed since "1c" can always be computed.

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Agreed to make 1em on region be identical to 1c (which is also identical to 100%).
