### ISSUE TITLE
Clarify intended rendering of background color when applied to a span.

### ISSUE THREAD

**Issue by andreastai** [w3c/ttml1#209]
An thread discussion on an issue opened for TTML 2 (https://github.com/w3c/ttml2/issues/150) points to the need for clarification in TTML 1 how background color should be rendereded when applied to a span element.

While a new mechanism to achieve a desired behaviour has to be defined for TTML 2 the starting point should be how the interpretation has to be for TTML 1. 

This issue is opened to separate the discussion on TTML 1 clarification and a new TTML 2 solution.

**Comment by andreastai** [comment]
I got (hopefully) a bit closer to the specified behavior in XSL-FO, which is a reference for TTML 1. (Thanks to [Tony Graham](https://github.com/tgraham-antenna) for pointing me to the line-stacking-strategy! This led me to important sections in the XSL-FO Spec.)

Two concepts seem to be the key to answer the question how background specified as background-color for inline-areas should be rendered: 
- The first concept was cited by [Nigel](https://github.com/w3c/ttml2/issues/150#issuecomment-192340644): background is rendered in the padding rectangle (in this case of an inline-area).
- The other concept is the line-stacking-strategy (see [Section 4.5 in XSL-FO](https://www.w3.org/TR/xsl/#area-line)). It defines how adjacent lines are positioned. The line-stacking-strategy plays an important role for how the “height” of a line can be calculated and which “extra” space is rendered at top and bottom of the text content in a line.

**Drawing of background to the padding rectangle**
In TTML a span element is equivalent to an XSL-FO inline formatting object that generates an inline area. As no padding can be specified for a span in TTML 1 the padding rectangle is equivalent to the content rectangle [see also XSL-FO Section 4.2.3](https://www.w3.org/TR/xsl/#area-geo). So we can say that the background of an inline-area generated by a span is rendered in its content rectangle. 

**Line-Stacking-Strategy**
The line-stacking-strategy is a property of a block-area. It defines how line-areas, that have inline-area children, are stacked. This implicitly also defines the “height” of a line or in other words its extent in the block-progression-direction (bpd).

In TTML the p element is an equivalent to an XSL-FO formatting object that generates a block area. Translated to XSL-FO the value of the line-stacking-property of the "p" block area is always "line-height" (it is inherited from the fo-block container generated by the region, see [9.3.3 Synchronic Flow Processing in TTML1](https://www.w3.org/TR/ttaf1-dfxp/#semantics-region-layout-step-2)).

In the following I will try to describe what this means for the "height" of a line and the background rendering specified for span elements. I cover only a simple use cases where font-family and font-size of the p and span element have the same values. Other cases may also be interesting  (e.g. where the font-size of span elements in a p vary) but for now it is helpful to concentrate on this very common (and also easier) use case.

Let’s assume the following:
-   A p element with a font-size set to 12px.
-   The line-height of the p is set to 24px.
-   The font-family is Arial.
-   The font-size of all span elements "in the" p element is derived from the p element (so also 12px). 

With these settings we assume that a presentation processor/renderer will use the same font for all text content in span elements. 

We now need to calculate the “height” or (bpd extent) of each inline-area child in a line-area. We can do so by summing up text-altitude and text-depth of the chosen font for that inline-area (the text altitude is added to the top of the dominant base line and text-depth to the bottom of the dominant baselinefont). The values for the text-altitude, text-depth and dominant baseline are defined in the font-table of the chosen font. 

Lets assume for our example that the sum of the text-altitude and text-depth of the chosen font match exactly the specified font-size (12px). The "height" of the content rectangle of the inline-area generated by all spans in a line-area of “our” p is therefore 12px. 

Another important geometric concept for the line-stacking is the allocation-rectangle. We have to distinguish two allocation rectangles: First the allocation rectangle of the line-area (which is an abstract representation of one line in a block-area) and then the allocation rectangle of the inline-area (generated by the spans in our case).

**Allocation-rectangle of the inline-area**: Regading its height/extent in the block progression direction the allocation-rectangle of an inline-area generated by a span is coincident with its content rectangle. Because the background of an inline-area generated by a span is rendered in the content-rectangle (same as the padding rectangle in this case) it can be said that the background does not extent outside of its allocation rectangle.

When the line-stacking-strategy is set to “line-height” (depending on the relation between font-height and line-height) extra space  may be added to top and bottom of the text content in a line. It is calculated for our example in the following way: the font-height of the inline area (12px) is subtracted from the line-height of the inline-area generated by the span. The line-height is derived from the p element (24px). The result of the subtraction (12px) is divided by two (6px). This is the half-leading and added outside (!) of the allocation-rectangle of the inline-area to top and bottom (or outside of before and after edge). This generates the “height” of a inline-area rectangle called the "expanded rectangle" (see [Section 4.5 in XSL-FO](https://www.w3.org/TR/xsl/#area-line)).

For the line-area (!) the extent of the allocation rectangle in the block progression direction (or its height) has now to be set to the minimum required to cover all expanded rectangles of its inline-area children. In our case this would be always 24px. When line-stacking-strategy is "line-height", no space-before or after is added to the line so the allocation rectangles of adjacent line-areas are stacked are back to back.

The above example may clarifiy that the background rendering for space added as half-leading (calculated from the difference between line-height and height of chosen font) is not affected by the background-color applied to a span element. The reason is that this space is added outside of the padding/content rectangle of the inline-area where the background-color for a span is rendered.

**Comment by skynavga** [comment]
Good description, see a few comments below.

On Tue, Mar 22, 2016 at 4:20 PM, Andreas Tai notifications@github.com
wrote:

> I got (hopefully) a bit closer to the specified behavior in XSL-FO, which
> is a reference for TTML 1. (Thanks to Tony Graham
> https://github.com/tgraham-antenna for pointing me to the
> line-stacking-strategy! This led me to important sections in the XSL-FO
> Spec.)
> 
> Two concepts seem to be the key to answer the question how background
> specified as background-color for inline-areas should be rendered:
> 
>    -
> 
>    The first concept was cited by Nigel
>    https://github.com/w3c/ttml2/issues/150#issuecomment-192340644:
>    background is rendered in the padding rectangle (in this case of an
>    inline-area).
>    -
> 
>    The other concept is the line-stacking-strategy (see Section 4.5 in
>    XSL-FO https://www.w3.org/TR/xsl/#area-line). It defines how
>    adjacent lines are positioned. The line-stacking-strategy plays an
>    important role for how the “height” of a line can be calculated and which
>    “extra” space is rendered at top and bottom of the text content in a line.
> 
> _Drawing of background to the padding rectangle_
> In TTML a span element is equivalent to an XSL-FO inline formatting object
> that generates an inline area. As no padding can be specified for a span in
> TTML 1 the padding rectangle is equivalent to the content rectangle see
> also XSL-FO Section 4.2.3 https://www.w3.org/TR/xsl/#area-geo. So we
> can say that the background of an inline-area generated by a span is
> rendered in its content rectangle.
> 
> _Line-Stacking-Strategy_
> The line-stacking-strategy is a property of a block-area. It defines how
> line-areas, that have inline-area children, are stacked. This implicitly
> also defines the “height” of a line or in other words its extent in the
> block-progression-direction (bpd).
> 
> In TTML the p element is an equivalent to an XSL-FO formatting object that
> generates a block area. Translated to XSL-FO the value of the
> line-stacking-property of the "p" block area is always "line-height" (it is
> inherited from the fo-block container generated by the region, see 9.3.3
> Synchronic Flow Processing in TTML1
> https://www.w3.org/TR/ttaf1-dfxp/#semantics-region-layout-step-2).
> 
> In the following I will try to describe what this means for the "height"
> of a line and the background rendering specified for span elements. I cover
> only a simple use cases where font-family and font-size of the p and span
> element have the same values. Other cases may also be interesting (e.g.
> where the font-size of span elements in a p vary) but for now it is helpful
> to concentrate on this very common (and also easier) use case.
> 
> Note also that in TTML1, tts:lineHeight applies only to p; however, in
> TTML2 we need to expand it to cover some spans, specifically, ruby text
> spans. This may lead us to expand the use of tts:lineHeight to arbitrary
> spans, in which case the description below would need to take account of
> inline areas having line height's less than or greater than the line height
> of the containing paragraph.
> 
> Let’s assume the following:
> - A p element with a font-size set to 12px.
> - The line-height of the p is set to 24px.
> - The font-family is Arial.
> - The font-size of all span elements "in the" p element is derived
>   from the p element (so also 12px).
> 
> With these settings we assume that a presentation processor/renderer will
> use the same font for all text content in span elements.
> 
> We now need to calculate the “height” or (bpd extent) of each inline-area
> child in a line-area. We can do so by summing up text-altitude and
> text-depth of the chosen font for that inline-area (the text altitude is
> added to the top of the dominant base line and text-depth to the bottom of
> the dominant baselinefont). The values for the text-altitude, text-depth
> and dominant baseline are defined in the font-table of the chosen font.
> 
> Lets assume for our example that the sum of the text-altitude and
> text-depth of the chosen font match exactly the specified font-size (12px).
> The "height" of the content rectangle of the inline-area generated by all
> spans in a line-area of “our” p is therefore 12px.
> 
> Another important geometric concept for the line-stacking is the
> allocation-rectangle. We have to distinguish two allocation rectangles:
> First the allocation rectangle of the line-area (which is an abstract
> representation of one line in a block-area) and then the allocation
> rectangle of the inline-area (generated by the spans in our case).
> 
> Better to say "of the inline-areas (generated by the  spans in our case)"
> in the previous sentence, since a span can generate more than one inline
> area, e.g., one inline area on Line N, another inline area on Line N+1,
> etc.
> 
> _Allocation-rectangle of the inline-area_: Regarding its height/extent in
> the block progression direction the allocation-rectangle of an inline-area
> generated by a span is coincident with its content rectangle. Because the
> background of an inline-area generated by a span is rendered in the
> content-rectangle (same as the padding rectangle in this case) it can be
> said that the background does not extent outside of its allocation
> rectangle.
> 
> When the line-stacking-strategy is set to “line-height” (depending on the
> relation between font-height and line-height) extra space may be added to
> top and bottom of the text content in a line. It is calculated for our
> example in the following way: the font-height of the inline area (12px) is
> subtracted from the line-height of the inline-area generated by the span.
> The line-height is derived from the p element (24px). The result of the
> subtraction (12px) is divided by two (6px). This is the half-leading and
> added outside (!) of the allocation-rectangle of the inline-area to top and
> bottom (or outside of before and after edge). This generates the “height”
> of a inline-area rectangle called the "expanded rectangle" (see Section
> 4.5 in XSL-FO https://www.w3.org/TR/xsl/#area-line).
> 
> For the line-area (!) the extent of the allocation rectangle in the block
> progression direction (or its height) has now to be set to the minimum
> required to cover all expanded rectangles of its inline-area children.
> 
> More accurately, the minimum required to cover:
- all expanded rectangles of its inline area children, _and_
- the expanded nominal requested line rectangle (as determined by the
  font of the p element).

In our case this would be always 24px. When line-stacking-strategy is

> "line-height", no space-before or after is added to the line so the
> allocation rectangles of adjacent line-areas are stacked are back to back.
> 
> The above example may clarifiy that the background rendering for space
> added as half-leading (calculated from the difference between line-height
> and height of chosen font) is not affected by the background-color applied
> to a span element. The reason is that this space is added outside of the
> padding/content rectangle of the inline-area where the background-color for
> a span is rendered.
> 
> Actually there is no rendering of the background color of a line area
> independently from the background color of the block area that contains the
> line areas. So, the following background color renderings may apply:
- background color of block area containing line areas is painted, which
  corresponds to the padding rectangle of the block area;
- for each inline area child IA of a line area child LA of a block area
  BA, a background color (if not transparent) is rendered in the padding
  rectangle of IA, which happens to be equal to the content rectangle of IA
  (in TTML1), which happens to be equal to the allocation rectangle of IA (in
  TTML1).

**Comment by andreastai** [comment]
Thanks for the comments!

> Note also that in TTML1, tts:lineHeight applies only to p; however, in TTML2 we need to expand it to cover some spans, specifically, ruby text spans. This may lead us to expand the use of tts:lineHeight to arbitrary spans, in which case the description below would need to take account of inline areas having line height's less than or greater than the line height of the containing paragraph.

That is right. We may have this kind of situation already in TTML 1 where the font-height of at least one inline-area in a line-area is greater than the font-height of the chosen font for the containing p element or where the font-height of all inline-area in a line-area is less than the font-height of the chosen font of the containing p. I left this out in the first description for simplicity but it may be useful to look at this cases when we discuss more generally the extent of a line in the block progression direction.

> Better to say "of the inline-areas (generated by the spans in our case)" in the previous sentence, since a span can generate more than one inline area, e.g., one inline area on Line N, another inline area on Line N+1, etc.

Good point. Can you  explain more where this should be improved? I could not see the difference in your comment and what was previously written.

> More accurately, the minimum required to cover: - all expanded rectangles of its inline area children, _and_ - the expanded nominal requested line rectangle (as determined by the font of the p element). 

Yes, correct. Also a point I left out to make the decription easier to follow. Your point is especially important where all inline-areas in a line-area have an expanded-rectangle with an extent less than the extent of expanded nominal requested line rectangle.

> Actually there is no rendering of the background color of a line area independently from the background color of the block area that contains the line areas. So, the following background color renderings may apply: 
> - background color of block area containing line areas is painted, which corresponds to the padding rectangle of the block area; 
> - for each inline area child IA of a line area child LA of a block area BA, a background color (if not transparent) is rendered in the padding rectangle of IA, which happens to be equal to the content rectangle of IA (in TTML1), which happens to be equal to the allocation rectangle of IA (in TTML1).

Good summary!

**Comment by nigelmegitt** [comment]
Thank you @tairt and @skynavga for this very helpful analysis. Even though it is not the behaviour the BBC would like to see in implementations, it is good to know that the height of the content rectangle is defined as the sum of the XSL-FO attributes [`text-altitude`](https://www.w3.org/TR/xsl11/#text-altitude) and [`text-depth`](https://www.w3.org/TR/xsl11/#text-depth), which may in turn be obtained from the font. I assume that since TTML does not specify mappings for these attributes the initial of `"use-font-metrics"` applies.

I think we can use this knowledge as a basis for what to do in TTML2 in the [original issue](https://github.com/w3c/ttml2/issues/150). 

Also, since padding on span is not defined in TTML1, I think it likely that as an implementation/adoption requirement other specifications could choose to state a rule that padding on spans may/should/shall be extended to the nearest ancestor line area for the purpose of determining a background area to draw.

I'd be interested to know if such a rule could cause us any difficulties in the future, for example in TTML2.

**Comment by andreastai** [comment]
@nigelmegitt

> Also, since padding on span is not defined in TTML1, I think it likely that as an implementation/adoption requirement other specifications could choose to state a rule that padding on spans may/should/shall be extended to the nearest ancestor line area for the purpose of determining a background area to draw.

Good (and important) question. A strict view would be:
- padding cannot be set explicitly in TTML
- for rendering environments that "know" the concept of padding the default should apply
  - or as alternative the default behavior of XSL-FO should apply
- the default in XSL-FO is 0 (pt) 
- a TTML presentation processor should not apply any padding to "inline-areas"

The other view would be more "relaxed" and say that the application of padding is implementation dependent. If this view is chosen as the "right" interpretation a TTML 1 Errata would be helpful. 

Two other points may be taken into account: 
- What do current TTML implementations do?
- What is the desired behavior?

In operation I have seen TTML caption implementations that add "some" padding to before and after edge of the equivalent of the content rectangle (most of them use CSS to define the rendering). This is also often the desired behavior from the editorial side because it makes the captions more readable. 

Therefore it may be good to give authors some guidance (and/or freedom) in TTML 1.

One option would be @nigelmegitt proposal. In this case it may be better to not refer to the line area because when other line-stacking-strategies are chosen space is added outside the allocation-rectangle of the line-area and I am not sure if you still consider this space as part of the line area (even they do not apply in TTML this wording may lead to confusion). Instead it could be said that the value for half-leading should be added as padding-before and padding-after value to an inline-area.

The other is to leave it open and say padding may be added to inline-areas and make it implementation dependent.

From my view the second option would be the better fit for TTML 1. The first option may work for some usage scenarios but not for all. This option could lead to undesired "masking" of video content when there is a big difference between line-height and font-height.

**Comment by nigelmegitt** [comment]
> I would view that behavior as non-compliant, since it so obviously varies
> from XSL-FO and CSS behavior. That is, the padding values are zero by
> default, so extending the padding would not comply with padding of 0.

That's reasonable. As long as it's notified as deliberate non-compliance I guess it's also okay to specify it as an implementation behaviour. Critically, I think it would not affect any text layout (though now I've worried myself about whether padding could affect the block progression dimension position of the first line in a region that has `tts:displayAlign="before"` etc). It's not ideal.

**Comment by nigelmegitt** [comment]
> The other is to leave it open and say padding may be added to inline-areas and make it implementation dependent.

This would leave enough room for the behaviour that we want to be defined for implementation subsets, e.g. HbbTV 2.0 implementations, so I'd accept it.

**Comment by skynavga** [comment]
On Wed, Mar 23, 2016 at 12:03 PM, Nigel Megitt notifications@github.com
wrote:

> I would view that behavior as non-compliant, since it so obviously varies
> from XSL-FO and CSS behavior. That is, the padding values are zero by
> default, so extending the padding would not comply with padding of 0.
> 
> That's reasonable. As long as it's notified as deliberate non-compliance I
> guess it's also okay to specify it as an implementation behaviour.
> Critically, I think it would not affect any text layout (though now I've
> worried myself about whether padding could affect the block progression
> dimension position of the first line in a region that has
> tts:displayAlign="before" etc). It's not ideal.
> 
> I think I will oppose a non-zero padding. However, I would be open to the
> possibility of allowing the content rectangle bpd to be implementation
> dependent. In fact, in the proposal found in [1], this would effectively
> equate with:

tts:bpdContent='auto'

which I defined as the (default) initial value.

[1] https://github.com/w3c/ttml2/issues/150#issuecomment-192490492

Thus a TTML1 implementation, which doesn't know about tts:bpdContent) could
implement the default ('auto'). Then TTML2 content could specify either
'bpdLine' or 'bpdLineLeaded' or 'bpdFont', etc,

Given that bpdFont = textAltitude + textDepth, that would be close to what
XSL-FO defines. Note that in practice, e.g., most browsers, CSS uses the
formula:

bpdFont = textAltitude + textDepth + textGap

so we might need both
- bpdFont (= textAltitude + textDepth); _and_
- bpdFontLeaded (= bpdFont + textGap)

**Comment by andreastai** [comment]
> However, I would be open to the possibility of allowing the content rectangle bpd to be implementation dependent.

I see a problem here because the before and end edge of the allocation rectangle of the inline area is coincident with the content rectangle (assuming that for inline-areas the "normal allocation-rectangle" apply). Spaces are added outside the allocation-rectangle so it will not help to increase the extent of the content-rectangle in the block progression direction.

**Comment by andreastai** [comment]
> Given that bpdFont = textAltitude + textDepth, that would be close to what XSL-FO defines. Note that in practice, e.g., most browsers, CSS uses the formula: bpdFont = textAltitude + textDepth + textGap

Do you mean that most browsers apply background-color to inline-area so that it covers textAltitude+textDepth+textGap,  where textGap is  `line-height - (textAlitude + textDepth)`? Can you point me to a browser that shows this behaviour?

See http://jsbin.com/kajoha/edit?html,css,output for an html/css example.

**Comment by skynavga** [comment]
On Thu, Mar 24, 2016 at 7:05 AM, Andreas Tai notifications@github.com
wrote:

> However, I would be open to the possibility of allowing the content
> rectangle bpd to be implementation dependent.
> 
> I see a problem here because the before and end edge of the allocation
> rectangle of the inline area is coincident with the content rectangle
> (assuming that for inline-areas the "normal allocation-rectangle" apply).
> Spaces are added outside the allocation-rectangle so it will not help to
> increase the extent of the content-rectangle in the block progression
> direction.
> 
> I think I see the problem you hint at here.

If we define the content rectangle bpd of inline areas to be, e.g.,
bpdLineLeaded, but the content rectangle bpd is used to compute
bpdLineLeaded (using the algorithm described in XSL-FO 1.1 §4.5 [1]), then
there is a circular definition problem.

[1] https://www.w3.org/TR/xsl/#area-line

To resolve this, we would need to partition the problem of defining content
rectangle bpd into two parts, depending on the value of tts:bpdContent.
This two-part algorithm applies only when tts:bpdContent is either bpdLine
or bpdLineLeaded; otherwise, the (default) one-part algorithm applies.

The one-part algorithm is as defined in [1]. The two-part algorithm extends
[1] as follows:
1. perform one-part algorithm [1] to determine the bpd of a line area,
   with and without leading;
2. for each inline area of line area, expand the bpd of the inline area
   (while maintaining same baseline placement) as required;

For example, say we have the following, with tts:bpdContent of
'bpdLineLeaded', and without taking into account any possible effects of
line/text gap metrics (for simplification):
- Line Area 1 (font size 12px, line height 24px)
  - Inline Area 1 (font size 12px)
  - Inline Area 2 (font size 18px)

Step (1), i.e., the one-part algorithm, will produce a bpdLine of 18px, and
bpdLineLeaded of 24px.

Step (2) will then set bpd of the content rectangle of both inline areas to
24px. In other words, the expanded-rectangles of inline areas are further
expanded to satisfy the desired bpdContent constraint.

If tts:bpdContent were instead 'bpdLine', then we would have:

Step (1) same as above.

Step (2) will then set bpd of the content rectangle of both inline areas to
18px.

As these examples demonstrate, the difference between bpdLine and
bpdLineLeaded in terms of drawing background color is as follows:
- bpdLine - all inline areas have background color drawn to size of
  largest font used on line;
- bpdLineLeaded - all inline areas have background color drawn to line's
  outer leading edges, thus resulting in background color of adjacent lines
  being co-terminus (in bpd).

**Comment by andreastai** [comment]
> If we define the content rectangle bpd of inline areas to be, e.g., bpdLineLeaded, but the content rectangle bpd is used to compute bpdLineLeaded (using the algorithm described in XSL-FO 1.1 §4.5 [1]), then there is a circular definition problem.

Yes, I think this is one part of the problem.

> Step (2) will then set bpd of the content rectangle of both inline areas to 24px. In other words, the expanded-rectangles of inline areas are further expanded to satisfy the desired bpdContent constraint.

I see the approach. All expanded-rectangles of inline-areas on one line will have the same height. 

I think the problem remains that the space is added outside of the allocation-rectangle. So you may need to say that instead of adding half-leading space to the outside of the allocation-rectangle you instead extend the before-edge and after-edge of the content rectangle by the same value.

There maybe still a problem to be solved later in TTML 2 when padding is applied.

**Comment by skynavga** [comment]
On Thu, Mar 24, 2016 at 12:16 PM, Andreas Tai notifications@github.com
wrote:

> If we define the content rectangle bpd of inline areas to be, e.g.,
> bpdLineLeaded, but the content rectangle bpd is used to compute
> bpdLineLeaded (using the algorithm described in XSL-FO 1.1 §4.5 [1]), then
> there is a circular definition problem.
> 
> Yes, I think this is one part of the problem.
> 
> Step (2) will then set bpd of the content rectangle of both inline areas
> to 24px. In other words, the expanded-rectangles of inline areas are
> further expanded to satisfy the desired bpdContent constraint.
> 
> I see the approach. All expanded-rectangles of inline-areas on one line
> will have the same height.
> 
> I think the problem remains that the space is added outside of the
> allocation-rectangle.
> 
> We need to be more precise here. By "space" I presume you mean
> "half-leading". But which allocation rectangle are you referring to? The
> child inline areas or the line area? I presume you mean the latter: leading
> is added outside the line area's allocation rectangle.
> 
> So you may need to say that instead of adding half-leading space to the
> outside of the allocation-rectangle you instead extend the before-edge and
> after-edge of the content rectangle by the same value.
> 
> When I said in step (2) of the proposed algorithm that "the
> expanded-rectangles of inline areas are further
> expanded to satisfy the desired bpdContent constraint", this is not adding
> leading (or half leading) to the inline area(s); rather, it is an
> additional expansion of the expanded rectangle (of each inline area) so
> that the before and after edges of each inline area are coincident with the
> before and after edges of the allocation rectangle of the line area (with
> or without having added line leading according to whether tts:bpdContent is
> 'bpdLineLeaded' (with) or 'bpdLine' (without).
> 
> There maybe still a problem to be solved later in TTML 2 when padding is
> applied.
> 
> Other than saying that any padding (if specified) extends outside the
> possibly extended expanded area, I don't see any particular problem from a
> semantic perspective.

That is, if, say, padding before and after are 2px on each inline area of a
line area, then the bpd of the padding rectangles of the two examples I
gave above would be as follows:
- bpdLineLeaded example - 24 + 2 + 2 = 28px
- bpdLine example = 18 + 2 + 2 = 22px

**Comment by andreastai** [comment]
> We need to be more precise here. By "space" I presume you mean "half-leading". But which allocation rectangle are you referring to? The child inline areas or the line area? 

Half-leading space of the inline-areas

> I presume you mean the latter: leading is added outside the line area's allocation rectangle.

That is not correct when the line-stacking-strategy is "line-height". In this case space-before and space-after (which would have the half-leading value when line-stacking-strategy is  font-height or max-height) is set to 0. The allocation-rectangle of the line-area when the line-stacking-strategy is "line-height" is the maximum-line-rectangle. This maximum-line-reactangle is amongst others the minimum rectangle required to enclose all expanded-line rectangles of inline-areas of that line. This expanded-line rectangles of inline-areas get their extent in the block-progression-direction by adding half-leading-space outside of their content-rectangles.

**Comment by skynavga** [comment]
On Wed, Mar 30, 2016 at 9:55 AM, Andreas Tai notifications@github.com
wrote:

> We need to be more precise here. By "space" I presume you mean
> "half-leading". But which allocation rectangle are you referring to? The
> child inline areas or the line area?
> 
> Half-leading space of the inline-areas
> 
> I presume you mean the latter: leading is added outside the line area's
> allocation rectangle.
> 
> That is not correct when the line-stacking-strategy is "line-height". In
> this case space-before and space-after (which would have the half-leading
> value when line-stacking-strategy is font-height or max-height) is set to
> 0. The allocation-rectangle of the line-area when the
> line-stacking-strategy is "line-height" is the maximum-line-rectangle. This
> maximum-line-reactangle is amongst others the minimum rectangle required to
> enclose all expanded-line rectangles of inline-areas of that line. This
> expanded-line rectangles of inline-areas get their extent in the
> block-progression-direction by adding half-leading-space outside of their
> content-rectangles.
> 
> Let's look at the definition of expanded rectangle:

The _expanded-rectangle_ of an inline-area is the rectangle ... whose

> before-edge and after-edge are outside those of its allocation-rectangle by
> a distance equal to either (a.) the half-leading, when the area's
> allocation-rectangle is specified to be the normal-allocation-rectangle by
> the description of the generating formatting object , or (b.) ....

Since we are discussing a case where we know that condition (a) applies,
i.e., normal-allocation-rectangle, then we need to interpret "half-leading"
in this context, which I contend is ambiguous, since it can mean either (1)
the half-leading HALF-LEADING(LA) that applies to the line area as a whole,
or (2) the half-leading HALF-LEADING(IA(_k_)) that applies to inline area
child _k_ of the line area.

The half-leading trait is not well defined in XSL-FO 1.1. In particular,
the definition of the line-height property §7.16.4 says:

In XSL the "line-height" property is used in determining the _half-leading_

> trait.

Now, we also know from §B.4 that line-height applies (independently) to
both fo:block and fo:inline, which means that the half-leading of the areas
generated by fo:block and the half-leading of the areas generated by
fo:inline (1) may be different, and (2) are derived from the line-height
property of the fo:block and fo:inline.

Now, my interpretation of half-leading in the definition of
expanded-rectangle (above) is that it refers to the half-leading of the _inline
area_ for which we are determining the expanded rectangle and not the _line
area_ parent of the inline area.

It seems to me that you are using a different interpretation of
half-leading, specifically, the half-leading of the line area parent.

**Comment by andreastai** [comment]
> Now, my interpretation of half-leading in the definition of expanded-rectangle (above) is that it refers to the half-leading of the _inline area_ for which we are determining the expanded rectangle and not the _line area_ parent of the inline area. It seems to me that you are using a different interpretation of half-leading, specifically, the half-leading of the line area parent.

I think we are on the same page. I just refered to your comment 

> I presume you mean the latter: leading is added outside the line area's allocation rectangle.

What I have been talking about in the previous comments is also the half-leading added to the inline area. So...

> Now, my interpretation of half-leading in the definition of expanded-rectangle (above) is that it refers to the half-leading of the _inline area_ for which we are determining the expanded rectangle and not the _line area_ parent of the inline area. 

...is also my interpretation.

The only semantic problem is that when this space is added outside of the content-rectangle-

> Step (2) will then set bpd of the content rectangle of both inline areas to 24px. In other words, the expanded-rectangles of inline areas are further expanded to satisfy the desired bpdContent constraint.

It may be good to have a picture. I will try working on this.

**Comment by andreastai** [comment]
Maybe the following image may be a good base for further clarification. It uses differrent font-sizes to make the principle clearer.

![line-area-spacingv1 2](https://cloud.githubusercontent.com/assets/4597762/14179356/25068d7c-f75f-11e5-97c0-d5ab06964797.png)

**Comment by skynavga** [comment]
TTWG (09/19/16) agrees that informative language should be added to TTML1 (by errata) that describes how XSL-FO/CSS (as defined) effectively allows/produces gaps (half leading) without extending bpd of content rectangle to line area edges. This is effectively current XSL-FO/CSS renderer behavior.

**Comment by andreastai** [comment]
This issue was discussed again in the TTWG meeting in London, January 2017. As far as I remember we decided to not add anything to TTML1. In this case this issue can be closed. But this may be confirmed by the meeting minutes.

**Comment by skynavga** [comment]
Implementing the Sep 19 decision will be very difficult, use a lot of prose, and ultimately be a paraphrase of XSL-FO/CSS, which will most likely be wrong. Suggest we do nothing and close this issue.
