### ISSUE TITLE
Use of fractional seconds in clock-time expression in smpte mode.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml1#213]
Need to address semantics of using a clock-time expression that contains fractional seconds when time base is smpte continuous mode. As there is no current prohibition on the presence of the fractional component in clock-time expressions, the current semantics of the seconds variable of the countedFrames expression is not well-defined.

[1] http://w3c.github.io/ttml2/spec/ttml2.html#time-expression-semantics-smpte

See also https://github.com/w3c/ttml2/issues/165.

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Need to make a change to TTML1 to deprecate fractional second components in time expressions in smpte timebase as per TTML2 - see edit that resolved w3c/ttml2#165.
