### ISSUE TITLE
Two value percentage fontSize not fully defined.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml1#215]
See w3c/ttml2#200

**Comment by skynavga** [comment]
Premise is false. Closing.

**Comment by nigelmegitt** [comment]
Premise still under discussion. Reopening.

**Comment by nigelmegitt** [comment]
[Meeting 2017-01-12] Implement as per w3c/ttml2#200.

**Comment by palemieux** [comment]
@nigelmegitt Please confirm that https://github.com/w3c/ttml2/pull/336/files meets your expectations since you have a number of outstanding comments on the PR.

**Comment by nigelmegitt** [comment]
@palemieux Yes, we discussed this at length in a meeting whose minutes I can't locate by searching - I recall @skynavga working through an example that took ~100% of my available brain capacity to process (and therefore I wasn't able to scribe it adequately) but resulted in me being convinced that there was no problem with that pull request.
