### ISSUE TITLE
Typos in Examples in Appendix O

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml1#223]
In Appendix O [1], there are a number of typos in the examples, e.g., bad </p end tag, bad xmlns declaration (for ttp).

[1] https://www.w3.org/TR/ttaf1-dfxp/#common-styling

Reported by Mike Dolan.

**Comment by skynavga** [comment]
Fixed in master branch. Need to follow-up with errata (adding label).

**Comment by nigelmegitt** [comment]
Please could you add a commit reference? Reopening since more work is required (i.e. the errata update).

**Comment by skynavga** [comment]
See 2977bd78cb53ae535111e1fed24fbe9e10ff5c80 and c099a534b7ec03f38e196c8bbd02a4da813ab638.

**Comment by nigelmegitt** [comment]
Thanks!

**Comment by skynavga** [comment]
Reclosing. See #226.

**Comment by nigelmegitt** [comment]
OK fine as long as this is tracked. I'll _actually_ close it now...
