### ISSUE TITLE
No begin times in Pop-On example in Appendix O.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml1#224]

**Comment by skynavga** [comment]
begin times are not required, since they are defaulted according to applicable time containment semantics

**Comment by nigelmegitt** [comment]
I agree with @skynavga : specifically the `timeContainer="seq"` on the `div` which means the first child element begins relative to its parent's begin, i.e. in this case at the same time as the `div` and the subsequent siblings begin relative to their previous sibling's computed end time, i.e. the begin plus the dur. So the times here are well defined.

**Comment by skynavga** [comment]
Add note to similar effect of "In the absence of an explicit setting of the begin time, SMIL defines time-container-dependent default values."

**Comment by mikedo** [comment]
Wouldn't the note be better in 10.2.1 where begin is defined? Readers may not come across the examples at the end to learn this.

**Comment by skynavga** [comment]
On Wed, Dec 21, 2016 at 2:26 PM, Michael A Dolan <notifications@github.com>
wrote:

> Wouldn't the note be better in 10.2.1 where begin is defined? Readers may
> not come across the examples at the end to learn this.
>
That is my plan.

**Comment by nigelmegitt** [comment]
Happy to support such a note. It would also be worth saying that the Epoch and any epochOffset are assumed to be provided by the document processing context, so people don't go looking for them in the TTML vocabulary.
