### ISSUE TITLE
Paint-On example improvement.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml1#225]
The example in O.3 (Paint-On) has a couple problems in addition to #223 :

1. A region is defined, but not referenced. Add to div, or delete and make it clear it is using the root container.
~~2. There are no spaces between the words.  Add xml:space and appropriate spaces.~~ (per https://github.com/w3c/ttml1/issues/225#issuecomment-268376595)

**Comment by palemieux** [comment]
> There are no spaces between the words. Add xml:space and appropriate spaces.

Should the white space between consecutive spans in the examples (combinations of spaces and newlines) be treated as a single white space character since linefeed-treatment="treat-as-space" and white-space-collapse="true" when xml:space="default"?

**Comment by skynavga** [comment]
On Tue, Dec 20, 2016 at 2:37 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> There are no spaces between the words. Add xml:space and appropriate
> spaces.
>
> Should the white space between consecutive spans in the examples
> (combinations of spaces and newlines) be treated as a single white space
> character since linefeed-treatment="treat-as-space" and
> white-space-collapse="true" when xml:space="default"?
>
Yes

**Comment by mikedo** [comment]
A bit subtle to accomplish a space between words by formatting the span elements in a tidy manner, but section 7.2.3 is certainly clear.  OK, then (2) is not broken, right?

**Comment by palemieux** [comment]
>  OK, then (2) is not broken, right?

It sounds like it.

**Comment by skynavga** [comment]
On Tue, Dec 20, 2016 at 3:15 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> OK, then (2) is not broken, right?
>
> It sounds like it.
>
Correct. Not broken w.r.t. spaces. Between the end of each span and the
beginning of the next span there are multiple whitespace characters
(SP,HT,LF,CR), each of which are mapped to SP and then collapsed to one SP.

**Comment by nigelmegitt** [comment]
If I understand correctly @skynavga you are saying that the "default" behaviour i.e. when `xml:space="default"` or it is unspecified, is that consecutive whitespace is normalised to a single space character? However the XML spec does not state this, [it](https://www.w3.org/TR/xml11/#sec-white-space) merely says:

> The value "default" signals that applications' default white-space processing modes are acceptable for this element;

And then:

> To simplify the tasks of applications, the XML processor MUST behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating all of the following to a single #xA character:

Where is the default behaviour defined for TTML? I would expect it to be coincident with whatever happens with XHTML.

**Comment by nigelmegitt** [comment]
I've answered my own question: https://www.w3.org/TR/ttml1/#content-attribute-space says

> The semantics of the value default are fixed to mean that when performing presentation processing of a Document Instance as described by 9.3.3 Synchronic Flow Processing, processing must occur as if the following properties were specified on the affected elements of an equivalent intermediate XSL-FO document:
>
>suppress-at-line-break="auto"
>linefeed-treatment="treat-as-space"
>white-space-collapse="true"
>white-space-treatment="ignore-if-surrounding-linefeed"

and [XSL-FO](https://www.w3.org/TR/xsl/#linefeed-treatment) says

> treat-as-space
> Specifies that any character flow object whose Unicode code point is U+000A (linefeed) shall be converted during the refinement process into a character flow object whose Unicode code point is U+0020 (space).

plus other relevant bits.

**Comment by skynavga** [comment]
On Thu, Dec 22, 2016 at 3:32 AM, Nigel Megitt <notifications@github.com>
wrote:

> If I understand correctly @skynavga <https://github.com/skynavga> you are
> saying that the "default" behaviour i.e. when xml:space="default" or it
> is unspecified, is that consecutive whitespace is normalised to a single
> space character? However the XML spec does not state this, it
> <https://www.w3.org/TR/xml11/#sec-white-space> merely says:
>
> The value "default" signals that applications' default white-space
> processing modes are acceptable for this element;
>
> And then:
>
> To simplify the tasks of applications, the XML processor MUST behave as if
> it normalized all line breaks in external parsed entities (including the
> document entity) on input, before parsing, by translating all of the
> following to a single #xA character:
>
> Where is the default behaviour defined for TTML? I would expect it to be
> coincident with whatever happens with XHTML.
>
https://www.w3.org/TR/ttaf1-dfxp/#content-attribute-space
