### ISSUE TITLE
Normative CSS2 reference changed to CSS2.1 in Second Edition

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml1#237]
The reference to CSS2 in Second Edition changed from:

> Bert Bos et al., Cascading Style Sheets, Level 2, W3C Recommendation, 12 May 1998. (See http://www.w3.org/TR/1998/REC-CSS2-19980512/.)

to 

> Bert Bos et al., Cascading Style Sheets, Level 2 Revision 1, W3C Recommendation, 07 June 2011. (See http://www.w3.org/TR/2011/REC-CSS2-20110607/.)

Two issues:

- there were normative changes between the two CSS versions, e.g. "16.6.1 The 'white-space' processing model" introduced in CSS2.1
- Second Edition continues to reference XSL 1.1, which references CSS2

Proposed resolution:

- revert normative reference to CSS2

**Comment by skynavga** [comment]
There is no bug here. TTML1 2nd Ed references CSS2.1. TTML1 also references XSL-FO 1.1, which references CSS2. So depending on the route to the specific reference, either CSS2.1 or CSS2 applies.

**Comment by skynavga** [comment]
Committed in #238.
