### ISSUE TITLE
tts:zIndex does not specify the root container zIndex value when "auto" is not specified

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml1#241]
Section 8.2.25 specifies that _the semantics of the value auto are those defined by [XSL 1.1], § 7.30.18, where the tt element is considered to establish the root stacking context_.

Does the `tt` element establish the stacking context even when `tts:zIndex` is not `auto`?

What is the computed `tts:zIndex` value for the root container? Does a region with `tts:zIndex < 0` appear underneath the root container?

**Comment by cconcolato** [comment]
The quoted text exists also in 10.2.56. Is there a similar issue on TTML2?

**Comment by nigelmegitt** [comment]
@cconcolato just to clarify: §10.2.56 is the definition of `tts:zIndex` in TTML2 not TTML1.

**Comment by nigelmegitt** [comment]
@palemieux My reading of the CSS [z-index](https://www.w3.org/TR/REC-CSS2/visuren.html#propdef-z-index) spec (as referenced by XSL 1.1) is that the stacking context is defined by the nearest ancestor element that defines a numerical stack level. In that case I would say, yes, the spec should state that the `tt` element defines a local stacking context for the purpose of resolving zIndex stacking levels in all cases. Then the comment that the `tt` element establishes the root stacking context can be removed from the sentence about `auto`.

**Comment by cconcolato** [comment]
@nigelmegitt yes, I meant 10.2.56 in TTML2.
