### ISSUE TITLE
Examples in section O use an unusual tts:displayAlign setting

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml1#254]
The examples in this section O are specifically named from the modes of CTA 608 closed captioning which implies certain behavior for the 3 modes. These 3 examples all take the initial value ("before") of tts:displayAlign, which causes initial text to appear in the top of the region. To align with 608 behavior it should be "after". Add tts:displayAlign="after" to the region definitions. (This difference is particularly noticeable for roll-up and paint-on.)

**Comment by nigelmegitt** [comment]
+1.

This makes no sense as is and we should add `tts:displayAlign="after"` to the examples.
