### ISSUE TITLE
State that no epoch or epochOffset is defined

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml1#266]
Issue split out from https://github.com/w3c/ttml1/issues/224#issuecomment-268787562

Somewhere in the timing attribute vocabulary section (possibly §10.2.4 timeContainer), add a statement along the lines of:

_The document processing context defines the applicable epoch and any epoch-related offsets to be used when establishing the synthetic document syncbase._

**Comment by palemieux** [comment]
@nigelmegitt How is the proposed note related to the following note at Annex N: _The media time base M is related to local real time R expressed in an arbitrary (implementation defined) epoch E as follows:_

**Comment by nigelmegitt** [comment]
@palemieux implementation defined is poorly specified, document processing context is more precise terminology. Essentially they're the same in my view.

**Comment by palemieux** [comment]
@nigelmegitt Shouldn't your proposed note therefore replace the Annex N prose re: epoch?

**Comment by nigelmegitt** [comment]
> Shouldn't your proposed note therefore replace the Annex N prose re: epoch?

@palemieux No, that wouldn't be my preference; rather I would change

> The media time base M is related to local real time R expressed in an arbitrary (implementation defined) epoch E as follows:

to

> The media time base M is related to local real time R expressed in _the applicable_ epoch E as follows:

(italics to show modification, not intended for the spec)

This would be in addition to making the proposed change in the timing attribute vocabulary section.

**Comment by palemieux** [comment]
@nigelmegitt Thanks. I have placed the suggested prose in Annex N since it is the only place where the term epoch is used.
