### ISSUE TITLE
Clarify timing concepts in relation to SMIL

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml1#300]
See w3c/ttml2#135 and pull request https://github.com/w3c/ttml2/pull/143 that led to [TTML2 §12.4.1 Media Timing](https://w3c.github.io/ttml2/spec/ttml2.html#semantics-media-timing) 

Should we also apply the same edits to TTML1 Third Edition? 

I see no reason why not. The SMIL reference would need to be made consistent with the TTML1 SMIL 2.1 reference, unless we also make TTML1 Third Edition reference SMIL 3. The rest of the section is equally true and useful for TTML1 as for TTML2.

**Comment by palemieux** [comment]
@nigelmegitt Shouldn't https://github.com/w3c/ttml2/issues/378 be resolved first, as it implies that TTML2 12.14.1 will be affected?

**Comment by nigelmegitt** [comment]
@palemieux They can be done independently, i.e. first do the timing concepts as per current TTML2 and then if necessary move the text as per w3c/ttml2#378 resolution, when that is known.

**Comment by palemieux** [comment]
> They can be done independently, i.e. first do the timing concepts as per current TTML2

@nigelmegitt Ok. Please go ahead and propose a PR.

**Comment by nigelmegitt** [comment]
@palemieux PR proposed.
