### ISSUE TITLE
Implicit durations of <set> and <br> not specified

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml1#310]
Section 10.4 does not specify the implicit duration of `br` and `set` elements.

I recommend using the same implicit duration as anonymous spans. Such an approach does not yield different results across the IMSC1 test vectors.

**Comment by nigelmegitt** [comment]
We may need to handle these two cases separately. In the example:

```xml
<p begin="10:00:00" timeContainer="seq">First line<br/>Second line</p>
```

there would be a reasonable case to make that the character content _and_ the `<br/>` should all be enclosed in the same anonymous span. This would have a completely different presentation to the two sets of character content each being enclosed in an anonymous span that is a sibling of the `<br/>`, but is probably what would be expected by most authors. Possibly this is a separate issue, but it seems like a dependency for resolving this issue.

The same consideration does not apply for `<set>` elements.

**Comment by palemieux** [comment]
@nigelmegitt My proposal is based on the following:

- I see the `br` as being equivalent to a LF if `xml:space="preserve"` and thus as a sibling to _First line_ and _Second line_

- I do not see a concrete use case for construction such as that at https://github.com/w3c/ttml1/issues/310#issuecomment-354575855 , so I do not think there have been authorial expectations

- Having the same implicit duration in seq containers for `br`, `set` and anonymous spans simplifies the code paths

**Comment by cconcolato** [comment]
`<set>` does not represent content, so why should it be treated like an anonymous span?

**Comment by palemieux** [comment]
> `set` does not represent content, so why should it be treated like an anonymous span?

To simplify code paths. I could not find conclusive evidence that either:

- `set` with no specified duration in a `seq` container corresponds to an actual use case (so the implicit duration is arbitrary); or
- SMIL/SVG specifies an implicit duration for `set` in a `seq` container 

Happy to be proven wrong.

**Comment by cconcolato** [comment]
FWIW, SVG does not support `seq` container and SMIL generally says (https://www.w3.org/TR/2001/REC-smil-animation-20010904/#DurAttribute)
> If the animation does not have a dur attribute, the simple duration is indefinite. Note that interpolation will not work if the simple duration is indefinite (although this may still be useful for `<set>` elements). See also Interpolation and indefinite simple durations.

It does not seem to depend on the parent time container.

**Comment by palemieux** [comment]
As another datapoint, SMIL2 specifies:

>If the media element has no timed children, it is described as a simple media element. [...] For simple media elements that specify continuous media (i.e. media with an inherent notion of time), the implicit duration is the intrinsic duration of the media itself - e.g. video and audio files have a defined duration. Note that clipBegin and clipEnd attributes on a media element can override the intrinsic media duration, and will define the implicit duration. See also the Media Object module. For simple media elements that specify discrete media (some times referred to as "static" media), the implicit duration is defined to be 0.

**Comment by nigelmegitt** [comment]
As far as I recall, SMIL media timing does not apply to any TTML elements.

**Comment by nigelmegitt** [comment]
> I do not see a concrete use case for construction such as that at https://github.com/w3c/ttml1/issues/310#issuecomment-354575855 , so I do not think there have been authorial expectations

@palemieux I don't think we can use this argument. We do not have full recollection of all use cases dealt with over the history of the specification and we have to deal with the possibilities presented by the specification as it is now. I would assume that whatever seemingly crazy cases you can think of, someone somewhere has authored a document containing them, unless we have evidence to the contrary.

**Comment by palemieux** [comment]
@nigelmegitt What are you proposing then?

**Comment by nigelmegitt** [comment]
@palemieux I'm proposing something like the implication of your first bullet in https://github.com/w3c/ttml1/issues/310#issuecomment-354666695 for `<br>`, which is to wrap it alongside any adjacent character content in the same (single) anonymous span so that they are co-timed.

**Comment by palemieux** [comment]
@nigelmegitt This cannot be done since `<br>` is turned into an actual linebreak well after timing is resolved.

**Comment by palemieux** [comment]
@nigelmegitt Also... why would anyone create something along the lines of `<p begin="10:00:00" timeContainer="seq">First line<br/>Second line</p>`?

**Comment by nigelmegitt** [comment]
> why would anyone create something along the lines of `<p begin="10:00:00" timeContainer="seq">First line<br/>Second line</p>`?

@palemieux I don't know, why wouldn't they?

> This cannot be done since `<br>` is turned into an actual linebreak well after timing is resolved.

I'm proposing a change to the way that content is wrapped in anonymous spans, which is before timing is resolved.

**Comment by palemieux** [comment]
> I don't know, why wouldn't they?

Because the implicit duration of anonymous spans in a `seq` container is zero and thus _First line_ and _Second line_ would not be displayed.

> I'm proposing a change to the way that content is wrapped in anonymous spans, which is before timing is resolved.

This would be a significant change to the processing model without a clear use case in mind.

**Comment by nigelmegitt** [comment]
> Because the implicit duration of anonymous spans in a `seq` container is zero and thus First line and Second line would not be displayed.

@palemieux Ah, right, I see, thank you. And as per this issue, the implicit duration of the `<br/>` is undefined, which means that depending on interpretation and implementation, the `<p>` presentation might pause indefinitely on an empty blank line, or that blank line might not ever be displayed. 

> This would be a significant change to the processing model without a clear use case in mind.

How so? I see it as no change to the general processing model, rather it is a change to what is defined to be included in the anonymous span.
