### ISSUE TITLE
Update Annex L intro per TTML2 modifications

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml1#314]
See https://github.com/w3c/ttml2/issues/478

**Comment by nigelmegitt** [comment]
Didn't I do this in #299? I certainly did _some_ of it.

**Comment by palemieux** [comment]
@nigelmegitt Yes, but https://github.com/w3c/ttml2/pull/517 also modified the introductory paragraph.

**Comment by nigelmegitt** [comment]
@palemieux ah right, thank you.

**Comment by palemieux** [comment]
@nigelmegitt Np. It would of course be much appreciated if you could pick-up the work, starting from #299 :)

**Comment by nigelmegitt** [comment]
@palemieux Noted, I will if I can in the next couple of days.

**Comment by nigelmegitt** [comment]
Since #299 has been merged I will start from master.

**Comment by nigelmegitt** [comment]
There appears to be only one change, and I'm not actually sure it is worth making. The TTML2 text says: 

> does not require dereferencing (and subsequent loading) of any
resource that is not contained in the same segment or access unit (or equivalent);

whereas the current TTML1 ED says:

> does not require dereferencing (and subsequent loading) of any
resources other than TTML Content;

Since TTML1 doesn't allow resources to be dereferenced at all, I think there's no useful change to make.

@palemieux if you're happy with that please could you close the issue?

**Comment by nigelmegitt** [comment]
@palemieux ping?

**Comment by palemieux** [comment]
> Since TTML1 doesn't allow resources to be dereferenced at all, I think there's no useful change to make.

@nigelmegitt Well... IMSC1 does (i.e. images), so I would rather see the same text as in TTML2.

**Comment by nigelmegitt** [comment]
> Well... IMSC1 does (i.e. images), so I would rather see the same text as in TTML2.

@palemieux That belongs in IMSC1 then, since it is an extension absent from TTML1.

**Comment by palemieux** [comment]
@nigelmegitt What about simply removing "resource that is not contained in the same segment or access unit (or equivalent)" since TTML1 does not support loadable resources?

**Comment by nigelmegitt** [comment]
@palemieux I'm missing something - I think that is a no-op compared to what is in TTML1 ED now.

**Comment by nigelmegitt** [comment]
@palemieux Please could you take another look at this and see if there's anything to do? It looks to me like there is nothing to do, but maybe I'm missing something.

**Comment by palemieux** [comment]
The current text of Annex L is not ideal, but informative and not incorrect.
