### ISSUE TITLE
Error in the substantive change list

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml1#359]
_update tts:lineHeight='normal' algorithm to match TTML2 (#355)_ should read _update tts:lineHeight='normal' algorithm to match TTML2 (#354)_

**Comment by nigelmegitt** [comment]
Agreed if we refer to the issues rather than the pull requests - #355 is the relevant pull request.

**Comment by skynavga** [comment]
I would suggest avoiding citation of either issue or PR. We didn't do this in prior edition changes and we don't do this in TTML2 changes either.

**Comment by palemieux** [comment]
The complete issue thread is useful to understanding the background of the modification, and contains links to the relevant PR.

**Comment by skynavga** [comment]
Yes, but it also comes under the rubric of "too much information can be confusing". The intent of the change files (at least in TTML1 and 2 so far) has been to provide a (very) brief (headline) summary of a change, and not provide full background.
