### ISSUE TITLE
Eliminate separate clear timing from dynamicFlow.

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml1#88]
I can see no justification for having separate clear timing in any of the examples from John Birch's original documents (the only hard evidence I can find in the history trail of a design discussion). The notion of a separate clear timer seems to have been added between the March 14 draft and March 21 draft without discussion on the public list. What is more, the presence of a separate clear interval seems at somewhat at odds with the behavioral requirement.

If I have a two line caption region , and I wish to flow the text through it, with text entering at a word rate and leaving at a line rate. Then I don't want a clear to occur until after two lines have been added, but then I want to clear the lines after each additional line is completed; which implies clear timing can't start until the region starts to overflow, so the first clear interval needs to be extended, and after that we want the clear interval to be synchronized with the fill interval which is based on irregular length words, so a single value seems inappropriate.

In the example flow below: The first clear/reflow occurs at t14, the next at t20, then at t27 and at t33  (clear intervals of 14, 6, 7 6), then we presumably want to clear the remaining two lines to be cleared in some manner.

T01 Alice

t02 Alice was

â€¦.

t06 Alice was beginning to get very

t07 Alice was beginning to get very 
       tired

â€¦.

t13 Alice was beginning to get very 
       tired of sitting by her sister on

t14 tired of sitting by her sister on 
       the
â€¦
T19 tired of sitting by her sister on 
        the bank and of having nothing

T20 the bank and of having nothing
        to
â€¦.

T26 the bank and of having nothing
        to do: once or twice she had

T27 to do: once or twice she had
        peeped

T33 peeped into the book her sister 
        was

T34 peeped into the book her sister 
        was reading

(raised by Sean Hayes on 2009-05-15)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/98

**Comment by skynavga** [comment]
Dynamic flow features are no longer part of TTML1.
